"""Second migration

Revision ID: 3e1d1b862bdd
Revises: ff1715741ccf
Create Date: 2023-10-27 12:11:35.278140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1d1b862bdd'
down_revision = 'ff1715741ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
